export const SCENE_KEYS = Object.freeze({
  PRELOAD_SCENE: "PRELOAD_SCENE",
  ANFANG_SCENE: "ANFANG_SCENE",
  ERSTER_SCENE: "ERSTER_SCENE",
  ZWEITER_SCENE: "ZWEITER_SCENE",
  DRITTER_SCENE: "DRITTER_SCENE",
  VIERTER_SCENE: "VIERTER_SCENE",
  ENDE_SCENE: "ENDE_SCENE",
  MENU_SCENE: "MENU_SCENE",
  TEXT_SCENE: "TEXT_SCENE",
});
